### ISSUE TITLE
Arduino crashes when attaching certain servos

### ISSUE THREAD

**Issue by apockill** [uArm-Developer/UArmForArduino#20]
When I do the following:

[sDetS0]
[sDetS1]
[sDetS2]
[sDetS3]
\*Stretch the arm as far as it can be stretched\*
[sAttS1]

The Arduino crashes: The robot's Buzzer rings, all servos are attached, and then the robot returns back to home position. This also happens in various other positions.

This kind of behavior could severly break uArm Creator Studio.

**Comment by UFactory-Alex** [comment]
I rolled back to the previous version, will solve this issue.
But theblow bug still exist.   
If Detach servo and move uArm to a position that `move_to` can not reach. Then Attach back the Servo. It would mess out the coordinate in uArm. Because uArm real range is bigger than the coordinate system range.
For now the best solution is:
when attach back the servo, Move uArm to closest point which can be reached by uArm's coordinate.
We didn't complete it yet.

**Comment by apockill** [comment]
Tested it. It's fixed.
